clear
close all

load('data.mat');

offset = 0;

% figure
% h = ploterr(1:5+offset, ...
%         strong_read(1, 1:5+offset), ...
%         [], ...
%         {strong_read(2, 1:5+offset), ...
%         strong_read(4, 1:5+offset)}, 'o-');
% set(h, 'lineWidth', 3)
% set(h, 'MarkerSize',10)
% hold on
% % figure
% h = ploterr(1:5+offset, ...
%         strong_write(1, 1:5+offset), ...
%         [], ...
%         {strong_write(2, 1:5+offset), ...
%         strong_write(4, 1:5+offset)});
% set(h, 'lineWidth', 3)
%
% % figure
% h = ploterr(1:5+offset, ...
%     ec_read(1, 1:5+offset), ...
%     [], ...
%     {ec_read(2, 1:5+offset), ...
%     ec_read(4, 1:5+offset)});
% set(h, 'lineWidth', 3)
%
% % figure
% h = ploterr(1:5+offset, ...
%     ec_write(1, 1:5+offset), ...
%     [], ...
%     {ec_write(2, 1:5+offset), ...
%     ec_write(4, 1:5+offset)});
% set(h, 'lineWidth', 3)

figure('units','normalized','position',[.1 .1 .4 .5])

plot(1:5, ...
        strong_read(1, (1:5)+offset), 'o-', 'lineWidth', 2, 'MarkerSize',7)

hold on
plot(1:5, ...
        strong_write(1, (1:5)+offset), 'o-', 'lineWidth', 2, 'MarkerSize',7)

plot(1:5, ...
        ec_read(1, (1:5)+offset), 'o-', 'lineWidth', 2, 'MarkerSize',7)

plot(1:5, ...
        ec_write(1, (1:5)+offset), 'o-', 'lineWidth', 2, 'MarkerSize',7)

set(gca,'fontsize',14)
xlabel('percentage of write operations')
ylabel('average latency(ms)');
axis([1 5 0 inf]);
legend({'strongly consistent read', 'strongly consistent write', ...
        'eventually consistent read', 'eventually consistent write'}, 'fontsize', 12);
ax = gca;
ax.XTick = [1 2 3 4 5];
ax.XTickLabel = {'0%', '25%', '50%', '75%', '100%'};
title('0ms latency added');
